// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// summarize_points
List summarize_points(NumericMatrix xyz);
RcppExport SEXP _houghPrimitives_summarize_points(SEXP xyzSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xyz(xyzSEXP);
    rcpp_result_gen = Rcpp::wrap(summarize_points(xyz));
    return rcpp_result_gen;
END_RCPP
}
// detect_tree_boles
List detect_tree_boles(NumericMatrix xyz, double min_radius, double max_radius, double min_height, int min_votes, bool vertical_only, bool label_points);
RcppExport SEXP _houghPrimitives_detect_tree_boles(SEXP xyzSEXP, SEXP min_radiusSEXP, SEXP max_radiusSEXP, SEXP min_heightSEXP, SEXP min_votesSEXP, SEXP vertical_onlySEXP, SEXP label_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xyz(xyzSEXP);
    Rcpp::traits::input_parameter< double >::type min_radius(min_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type max_radius(max_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type min_height(min_heightSEXP);
    Rcpp::traits::input_parameter< int >::type min_votes(min_votesSEXP);
    Rcpp::traits::input_parameter< bool >::type vertical_only(vertical_onlySEXP);
    Rcpp::traits::input_parameter< bool >::type label_points(label_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_tree_boles(xyz, min_radius, max_radius, min_height, min_votes, vertical_only, label_points));
    return rcpp_result_gen;
END_RCPP
}
// detect_spheres
List detect_spheres(NumericMatrix xyz, double min_radius, double max_radius, int min_votes, bool label_points);
RcppExport SEXP _houghPrimitives_detect_spheres(SEXP xyzSEXP, SEXP min_radiusSEXP, SEXP max_radiusSEXP, SEXP min_votesSEXP, SEXP label_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xyz(xyzSEXP);
    Rcpp::traits::input_parameter< double >::type min_radius(min_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type max_radius(max_radiusSEXP);
    Rcpp::traits::input_parameter< int >::type min_votes(min_votesSEXP);
    Rcpp::traits::input_parameter< bool >::type label_points(label_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_spheres(xyz, min_radius, max_radius, min_votes, label_points));
    return rcpp_result_gen;
END_RCPP
}
// detect_planes
List detect_planes(NumericMatrix xyz, double distance_threshold, int min_votes, int max_iterations, bool label_points);
RcppExport SEXP _houghPrimitives_detect_planes(SEXP xyzSEXP, SEXP distance_thresholdSEXP, SEXP min_votesSEXP, SEXP max_iterationsSEXP, SEXP label_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xyz(xyzSEXP);
    Rcpp::traits::input_parameter< double >::type distance_threshold(distance_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type min_votes(min_votesSEXP);
    Rcpp::traits::input_parameter< int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type label_points(label_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_planes(xyz, distance_threshold, min_votes, max_iterations, label_points));
    return rcpp_result_gen;
END_RCPP
}
// detect_lines
List detect_lines(NumericMatrix xyz, double distance_threshold, int min_votes, double min_length, int max_iterations, bool in_scene, bool label_points);
RcppExport SEXP _houghPrimitives_detect_lines(SEXP xyzSEXP, SEXP distance_thresholdSEXP, SEXP min_votesSEXP, SEXP min_lengthSEXP, SEXP max_iterationsSEXP, SEXP in_sceneSEXP, SEXP label_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xyz(xyzSEXP);
    Rcpp::traits::input_parameter< double >::type distance_threshold(distance_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type min_votes(min_votesSEXP);
    Rcpp::traits::input_parameter< double >::type min_length(min_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type in_scene(in_sceneSEXP);
    Rcpp::traits::input_parameter< bool >::type label_points(label_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_lines(xyz, distance_threshold, min_votes, min_length, max_iterations, in_scene, label_points));
    return rcpp_result_gen;
END_RCPP
}
// detect_cylinders
List detect_cylinders(NumericMatrix xyz, double min_radius, double max_radius, double min_length, int min_votes, bool label_points);
RcppExport SEXP _houghPrimitives_detect_cylinders(SEXP xyzSEXP, SEXP min_radiusSEXP, SEXP max_radiusSEXP, SEXP min_lengthSEXP, SEXP min_votesSEXP, SEXP label_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xyz(xyzSEXP);
    Rcpp::traits::input_parameter< double >::type min_radius(min_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type max_radius(max_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type min_length(min_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type min_votes(min_votesSEXP);
    Rcpp::traits::input_parameter< bool >::type label_points(label_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_cylinders(xyz, min_radius, max_radius, min_length, min_votes, label_points));
    return rcpp_result_gen;
END_RCPP
}
// detect_cubes
List detect_cubes(NumericMatrix xyz, double min_size, double max_size, int min_votes, double plane_threshold, bool label_points);
RcppExport SEXP _houghPrimitives_detect_cubes(SEXP xyzSEXP, SEXP min_sizeSEXP, SEXP max_sizeSEXP, SEXP min_votesSEXP, SEXP plane_thresholdSEXP, SEXP label_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xyz(xyzSEXP);
    Rcpp::traits::input_parameter< double >::type min_size(min_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type max_size(max_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type min_votes(min_votesSEXP);
    Rcpp::traits::input_parameter< double >::type plane_threshold(plane_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type label_points(label_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_cubes(xyz, min_size, max_size, min_votes, plane_threshold, label_points));
    return rcpp_result_gen;
END_RCPP
}
// detect_cuboids
List detect_cuboids(NumericMatrix xyz, double min_width, double max_width, double min_height, double max_height, int min_votes, double plane_threshold, bool label_points);
RcppExport SEXP _houghPrimitives_detect_cuboids(SEXP xyzSEXP, SEXP min_widthSEXP, SEXP max_widthSEXP, SEXP min_heightSEXP, SEXP max_heightSEXP, SEXP min_votesSEXP, SEXP plane_thresholdSEXP, SEXP label_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xyz(xyzSEXP);
    Rcpp::traits::input_parameter< double >::type min_width(min_widthSEXP);
    Rcpp::traits::input_parameter< double >::type max_width(max_widthSEXP);
    Rcpp::traits::input_parameter< double >::type min_height(min_heightSEXP);
    Rcpp::traits::input_parameter< double >::type max_height(max_heightSEXP);
    Rcpp::traits::input_parameter< int >::type min_votes(min_votesSEXP);
    Rcpp::traits::input_parameter< double >::type plane_threshold(plane_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type label_points(label_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_cuboids(xyz, min_width, max_width, min_height, max_height, min_votes, plane_threshold, label_points));
    return rcpp_result_gen;
END_RCPP
}
// detect_cones
List detect_cones(NumericMatrix xyz, double min_radius, double max_radius, double min_height, double max_height, int min_votes, double angle_threshold, bool label_points);
RcppExport SEXP _houghPrimitives_detect_cones(SEXP xyzSEXP, SEXP min_radiusSEXP, SEXP max_radiusSEXP, SEXP min_heightSEXP, SEXP max_heightSEXP, SEXP min_votesSEXP, SEXP angle_thresholdSEXP, SEXP label_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xyz(xyzSEXP);
    Rcpp::traits::input_parameter< double >::type min_radius(min_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type max_radius(max_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type min_height(min_heightSEXP);
    Rcpp::traits::input_parameter< double >::type max_height(max_heightSEXP);
    Rcpp::traits::input_parameter< int >::type min_votes(min_votesSEXP);
    Rcpp::traits::input_parameter< double >::type angle_threshold(angle_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type label_points(label_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_cones(xyz, min_radius, max_radius, min_height, max_height, min_votes, angle_threshold, label_points));
    return rcpp_result_gen;
END_RCPP
}
// detect_circles_2d
List detect_circles_2d(NumericMatrix xy, double min_radius, double max_radius, double distance_threshold, int min_votes, int max_iterations, bool label_points);
RcppExport SEXP _houghPrimitives_detect_circles_2d(SEXP xySEXP, SEXP min_radiusSEXP, SEXP max_radiusSEXP, SEXP distance_thresholdSEXP, SEXP min_votesSEXP, SEXP max_iterationsSEXP, SEXP label_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xy(xySEXP);
    Rcpp::traits::input_parameter< double >::type min_radius(min_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type max_radius(max_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type distance_threshold(distance_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type min_votes(min_votesSEXP);
    Rcpp::traits::input_parameter< int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type label_points(label_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_circles_2d(xy, min_radius, max_radius, distance_threshold, min_votes, max_iterations, label_points));
    return rcpp_result_gen;
END_RCPP
}
// detect_ellipses_2d
List detect_ellipses_2d(NumericMatrix xy, double min_radius, double max_radius, double distance_threshold, int min_votes, int max_iterations, bool label_points);
RcppExport SEXP _houghPrimitives_detect_ellipses_2d(SEXP xySEXP, SEXP min_radiusSEXP, SEXP max_radiusSEXP, SEXP distance_thresholdSEXP, SEXP min_votesSEXP, SEXP max_iterationsSEXP, SEXP label_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xy(xySEXP);
    Rcpp::traits::input_parameter< double >::type min_radius(min_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type max_radius(max_radiusSEXP);
    Rcpp::traits::input_parameter< double >::type distance_threshold(distance_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type min_votes(min_votesSEXP);
    Rcpp::traits::input_parameter< int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type label_points(label_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_ellipses_2d(xy, min_radius, max_radius, distance_threshold, min_votes, max_iterations, label_points));
    return rcpp_result_gen;
END_RCPP
}
// detect_rectangles_2d
List detect_rectangles_2d(NumericMatrix xy, double min_width, double max_width, double distance_threshold, int min_votes, int max_iterations, bool label_points);
RcppExport SEXP _houghPrimitives_detect_rectangles_2d(SEXP xySEXP, SEXP min_widthSEXP, SEXP max_widthSEXP, SEXP distance_thresholdSEXP, SEXP min_votesSEXP, SEXP max_iterationsSEXP, SEXP label_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xy(xySEXP);
    Rcpp::traits::input_parameter< double >::type min_width(min_widthSEXP);
    Rcpp::traits::input_parameter< double >::type max_width(max_widthSEXP);
    Rcpp::traits::input_parameter< double >::type distance_threshold(distance_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type min_votes(min_votesSEXP);
    Rcpp::traits::input_parameter< int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type label_points(label_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_rectangles_2d(xy, min_width, max_width, distance_threshold, min_votes, max_iterations, label_points));
    return rcpp_result_gen;
END_RCPP
}
// detect_squares_2d
List detect_squares_2d(NumericMatrix xy, double min_size, double max_size, double distance_threshold, int min_votes, int max_iterations, bool label_points);
RcppExport SEXP _houghPrimitives_detect_squares_2d(SEXP xySEXP, SEXP min_sizeSEXP, SEXP max_sizeSEXP, SEXP distance_thresholdSEXP, SEXP min_votesSEXP, SEXP max_iterationsSEXP, SEXP label_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xy(xySEXP);
    Rcpp::traits::input_parameter< double >::type min_size(min_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type max_size(max_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type distance_threshold(distance_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type min_votes(min_votesSEXP);
    Rcpp::traits::input_parameter< int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< bool >::type label_points(label_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_squares_2d(xy, min_size, max_size, distance_threshold, min_votes, max_iterations, label_points));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_houghPrimitives_summarize_points", (DL_FUNC) &_houghPrimitives_summarize_points, 1},
    {"_houghPrimitives_detect_tree_boles", (DL_FUNC) &_houghPrimitives_detect_tree_boles, 7},
    {"_houghPrimitives_detect_spheres", (DL_FUNC) &_houghPrimitives_detect_spheres, 5},
    {"_houghPrimitives_detect_planes", (DL_FUNC) &_houghPrimitives_detect_planes, 5},
    {"_houghPrimitives_detect_lines", (DL_FUNC) &_houghPrimitives_detect_lines, 7},
    {"_houghPrimitives_detect_cylinders", (DL_FUNC) &_houghPrimitives_detect_cylinders, 6},
    {"_houghPrimitives_detect_cubes", (DL_FUNC) &_houghPrimitives_detect_cubes, 6},
    {"_houghPrimitives_detect_cuboids", (DL_FUNC) &_houghPrimitives_detect_cuboids, 8},
    {"_houghPrimitives_detect_cones", (DL_FUNC) &_houghPrimitives_detect_cones, 8},
    {"_houghPrimitives_detect_circles_2d", (DL_FUNC) &_houghPrimitives_detect_circles_2d, 7},
    {"_houghPrimitives_detect_ellipses_2d", (DL_FUNC) &_houghPrimitives_detect_ellipses_2d, 7},
    {"_houghPrimitives_detect_rectangles_2d", (DL_FUNC) &_houghPrimitives_detect_rectangles_2d, 7},
    {"_houghPrimitives_detect_squares_2d", (DL_FUNC) &_houghPrimitives_detect_squares_2d, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_houghPrimitives(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
