# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simple point cloud summary
#' 
#' @param xyz A matrix with 3 columns (X, Y, Z coordinates)
#' @return A list with summary statistics
#' @export
summarize_points <- function(xyz) {
    .Call(`_houghPrimitives_summarize_points`, xyz)
}

#' Detect tree boles (cylindrical trunks) in point cloud data
#' 
#' @param xyz A matrix with 3 columns (X, Y, Z coordinates)
#' @param min_radius Minimum trunk radius in meters
#' @param max_radius Maximum trunk radius in meters
#' @param min_height Minimum visible trunk height in meters
#' @param min_votes Minimum number of points required to detect a tree
#' @param vertical_only If TRUE, only detect vertical cylinders
#' @param label_points If TRUE, label all points with tree ID
#' @return A list with detected trees and optionally labeled points
#' @export
detect_tree_boles <- function(xyz, min_radius = 0.05, max_radius = 0.5, min_height = 1.0, min_votes = 30L, vertical_only = TRUE, label_points = FALSE) {
    .Call(`_houghPrimitives_detect_tree_boles`, xyz, min_radius, max_radius, min_height, min_votes, vertical_only, label_points)
}

#' Detect spheres in point cloud data using 3D Hough transform
#' 
#' @param xyz A matrix with 3 columns (X, Y, Z coordinates)
#' @param min_radius Minimum sphere radius
#' @param max_radius Maximum sphere radius
#' @param min_votes Minimum number of points required to detect a sphere
#' @param label_points If TRUE, label all points with sphere ID
#' @return A list with detected spheres and optionally labeled points
#' @export
detect_spheres <- function(xyz, min_radius = 0.1, max_radius = 2.0, min_votes = 30L, label_points = FALSE) {
    .Call(`_houghPrimitives_detect_spheres`, xyz, min_radius, max_radius, min_votes, label_points)
}

#' Detect planes in point cloud data using RANSAC
#' 
#' @param xyz A matrix with 3 columns (X, Y, Z coordinates)
#' @param distance_threshold Maximum distance from plane for inliers
#' @param min_votes Minimum number of points required to detect a plane
#' @param max_iterations Maximum RANSAC iterations
#' @param label_points If TRUE, label all points with plane ID
#' @return A list with detected planes and optionally labeled points
#' @export
detect_planes <- function(xyz, distance_threshold = 0.1, min_votes = 100L, max_iterations = 1000L, label_points = FALSE) {
    .Call(`_houghPrimitives_detect_planes`, xyz, distance_threshold, min_votes, max_iterations, label_points)
}

#' Detect 3D lines in point cloud data
#' 
#' @param xyz A matrix with 3 columns (X, Y, Z coordinates)
#' @param distance_threshold Maximum distance from line for inliers
#' @param min_votes Minimum number of points required to detect a line
#' @param min_length Minimum line length
#' @param max_iterations Maximum RANSAC iterations
#' @param in_scene If TRUE, assumes lines exist in complex scene (stricter). If FALSE, optimized for line-only detection (more aggressive)
#' @param label_points If TRUE, label all points with line ID
#' @return A list with detected lines and optionally labeled points
#' @export
detect_lines <- function(xyz, distance_threshold = 0.05, min_votes = 20L, min_length = 0.5, max_iterations = 500L, in_scene = TRUE, label_points = FALSE) {
    .Call(`_houghPrimitives_detect_lines`, xyz, distance_threshold, min_votes, min_length, max_iterations, in_scene, label_points)
}

#' Detect general cylinders (not just vertical) in point cloud data
#' 
#' @param xyz A matrix with 3 columns (X, Y, Z coordinates)
#' @param min_radius Minimum cylinder radius
#' @param max_radius Maximum cylinder radius
#' @param min_length Minimum cylinder length
#' @param min_votes Minimum number of points required
#' @param label_points If TRUE, label all points with cylinder ID
#' @return A list with detected cylinders and optionally labeled points
#' @export
detect_cylinders <- function(xyz, min_radius = 0.1, max_radius = 2.0, min_length = 1.0, min_votes = 50L, label_points = FALSE) {
    .Call(`_houghPrimitives_detect_cylinders`, xyz, min_radius, max_radius, min_length, min_votes, label_points)
}

#' Detect cubes in point cloud data
#' 
#' @param xyz A matrix with 3 columns (X, Y, Z coordinates)
#' @param min_size Minimum cube side length
#' @param max_size Maximum cube side length
#' @param min_votes Minimum number of points required per cube
#' @param plane_threshold Distance threshold for plane detection
#' @param label_points If TRUE, label all points with cube ID
#' @return A list with detected cubes and optionally labeled points
#' @export
detect_cubes <- function(xyz, min_size = 0.3, max_size = 3.0, min_votes = 100L, plane_threshold = 0.05, label_points = FALSE) {
    .Call(`_houghPrimitives_detect_cubes`, xyz, min_size, max_size, min_votes, plane_threshold, label_points)
}

#' Detect cuboids (rectangular boxes) in point cloud data
#' 
#' @param xyz A matrix with 3 columns (X, Y, Z coordinates)
#' @param min_width Minimum cuboid width
#' @param max_width Maximum cuboid width
#' @param min_height Minimum cuboid height
#' @param max_height Maximum cuboid height
#' @param min_votes Minimum number of points required per cuboid
#' @param plane_threshold Distance threshold for plane detection
#' @param label_points If TRUE, label all points with cuboid ID
#' @return A list with detected cuboids and optionally labeled points
#' @export
detect_cuboids <- function(xyz, min_width = 0.5, max_width = 10.0, min_height = 0.5, max_height = 10.0, min_votes = 150L, plane_threshold = 0.1, label_points = FALSE) {
    .Call(`_houghPrimitives_detect_cuboids`, xyz, min_width, max_width, min_height, max_height, min_votes, plane_threshold, label_points)
}

#' Detect cones in 3D point cloud
#' 
#' @param xyz A matrix with 3 columns (X, Y, Z coordinates)
#' @param min_radius Minimum base radius in meters
#' @param max_radius Maximum base radius in meters
#' @param min_height Minimum cone height in meters
#' @param max_height Maximum cone height in meters
#' @param min_votes Minimum number of points to form a cone
#' @param angle_threshold Opening half-angle threshold in radians (default: 0.3 ~ 17 degrees)
#' @param label_points If TRUE, return point labels
#' @return A list with detected cones
#' @export
detect_cones <- function(xyz, min_radius = 0.1, max_radius = 2.0, min_height = 0.5, max_height = 10.0, min_votes = 50L, angle_threshold = 0.3, label_points = FALSE) {
    .Call(`_houghPrimitives_detect_cones`, xyz, min_radius, max_radius, min_height, max_height, min_votes, angle_threshold, label_points)
}

#' Detect circles in 2D point data using RANSAC
#'
#' Uses a RANSAC approach with 3-point circumscribed circle fitting to detect
#' circular patterns in 2D point sets. Iteratively detects circles, removing
#' inlier points after each detection.
#'
#' @param xy A matrix with 2 columns (X, Y coordinates)
#' @param min_radius Minimum circle radius
#' @param max_radius Maximum circle radius
#' @param distance_threshold Maximum distance from circle boundary for inliers
#' @param min_votes Minimum number of points required to detect a circle
#' @param max_iterations Maximum RANSAC iterations per detection
#' @param label_points If TRUE, label all points with circle ID
#' @return A list with detected circles and optionally labeled points
#' @export
detect_circles_2d <- function(xy, min_radius = 0.1, max_radius = 10.0, distance_threshold = 0.1, min_votes = 20L, max_iterations = 1000L, label_points = FALSE) {
    .Call(`_houghPrimitives_detect_circles_2d`, xy, min_radius, max_radius, distance_threshold, min_votes, max_iterations, label_points)
}

#' Detect ellipses in 2D point data using RANSAC
#'
#' Uses RANSAC with 5-point algebraic conic fitting and Sampson distance
#' for inlier evaluation. Iteratively detects ellipses, removing inlier
#' points after each detection.
#'
#' @param xy A matrix with 2 columns (X, Y coordinates)
#' @param min_radius Minimum semi-minor axis length
#' @param max_radius Maximum semi-major axis length
#' @param distance_threshold Maximum approximate distance from ellipse for inliers
#' @param min_votes Minimum number of points required to detect an ellipse
#' @param max_iterations Maximum RANSAC iterations per detection
#' @param label_points If TRUE, label all points with ellipse ID
#' @return A list with detected ellipses and optionally labeled points
#' @export
detect_ellipses_2d <- function(xy, min_radius = 0.1, max_radius = 10.0, distance_threshold = 0.1, min_votes = 30L, max_iterations = 2000L, label_points = FALSE) {
    .Call(`_houghPrimitives_detect_ellipses_2d`, xy, min_radius, max_radius, distance_threshold, min_votes, max_iterations, label_points)
}

#' Detect rectangles in 2D point data using RANSAC
#'
#' Uses a RANSAC approach to detect rectangular patterns in 2D point sets.
#' Samples 3 points to define edge direction and width, then validates by
#' counting inliers along all 4 edges. Iteratively detects rectangles,
#' removing inlier points after each detection.
#'
#' @param xy A matrix with 2 columns (X, Y coordinates)
#' @param min_width Minimum rectangle dimension (applies to both width and height)
#' @param max_width Maximum rectangle dimension (applies to both width and height)
#' @param distance_threshold Maximum distance from rectangle edge for inliers
#' @param min_votes Minimum number of points required to detect a rectangle
#' @param max_iterations Maximum RANSAC iterations per detection
#' @param label_points If TRUE, label all points with rectangle ID
#' @return A list with detected rectangles and optionally labeled points
#' @export
detect_rectangles_2d <- function(xy, min_width = 0.5, max_width = 10.0, distance_threshold = 0.1, min_votes = 20L, max_iterations = 1000L, label_points = FALSE) {
    .Call(`_houghPrimitives_detect_rectangles_2d`, xy, min_width, max_width, distance_threshold, min_votes, max_iterations, label_points)
}

#' Detect squares in 2D point data using RANSAC
#'
#' Uses the same approach as rectangle detection but with an additional
#' constraint that width and height must be approximately equal (within
#' 15\% tolerance). Iteratively detects squares, removing inlier points
#' after each detection.
#'
#' @param xy A matrix with 2 columns (X, Y coordinates)
#' @param min_size Minimum square side length
#' @param max_size Maximum square side length
#' @param distance_threshold Maximum distance from square edge for inliers
#' @param min_votes Minimum number of points required to detect a square
#' @param max_iterations Maximum RANSAC iterations per detection
#' @param label_points If TRUE, label all points with square ID
#' @return A list with detected squares and optionally labeled points
#' @export
detect_squares_2d <- function(xy, min_size = 0.5, max_size = 10.0, distance_threshold = 0.1, min_votes = 20L, max_iterations = 1000L, label_points = FALSE) {
    .Call(`_houghPrimitives_detect_squares_2d`, xy, min_size, max_size, distance_threshold, min_votes, max_iterations, label_points)
}

